aedi: use absolute path to patch executable
this is a workaround for pycharm specific exception

Traceback (most recent call last):
  File "/Volumes/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 108, in starts_with_python_shebang
    with open(path) as f:
IsADirectoryError: [Errno 21] Is a directory: 'patch'

it's caused by presence of patch directory in repository root which is a working directory in most cases during debug session